# == This file defines the page layouts for new pages.
#
# For further informations please see http://guides.alchemy-cms.com/create_page_layouts.html

- name: exhibition_theme_page
  unique: false
  elements: [text, image, rich_image, section, quote, intro, embed, image_compare]
- name: exhibition_index_page
  unique: false
  elements: [foyer_card, featured_exhibition]
- name: exhibition_credit_page
  unique: false
  elements: [credit_intro, text, image, rich_image]
