<%
if ENV.key?('VCAP_SERVICES')
  services = JSON.parse(ENV['VCAP_SERVICES'])
  if services.key?('user-provided')
    redis_config = services['user-provided'].find { |val| val.key?('name') && val['name'].match(/redis/) }
  end
  if redis_config.nil? && services.key?('redis-2.2')
    redis_config = services['redis-2.2'].first
  end
end
fail 'No Redis service found in environment.' if redis_config.nil?
redis_url = "redis://#{redis_config['credentials']['name']}:#{redis_config['credentials']['password']}@#{redis_config['credentials']['hostname']}:#{redis_config['credentials']['port']}/0/cache"
%>
production:
  url: "<%= redis_url %>"
